### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by trypsynth** [blindpandas/docr#1]
This is an extremely useful crate. I know the primary reason it was created is for use in Bookworm, but I can see it having some uses outside of that, too. In fact, I already have one in mind. Is it at all possible to publish this crate to crates.io?

**Comment by mush42** [comment]
@TheQuinbox 

Is it strictly necessary?

I think Cargo allows you to depend on and install crates from git repositories.

**Comment by trypsynth** [comment]
It does, but what if you push a breaking change? Cargo allows for proper versioning and whatnot.
